name: Deploy to Development

on:
  push:
    branches:
      - development

permissions:
  id-token: write
  contents: read
jobs:
  unit-tests:
    name: Run Unit Tests
    uses: ./.github/workflows/reusable-test.yml

  deploy-development:
    name: Deploy to Development
    needs: unit-tests
    uses: ./.github/workflows/reusable-aws-deploy.yml
    with:
      environment: development
      version: ${{ github.sha }}
    secrets: inherit