name: Deploy to Development

on:
  push:
    branches:
      - development

permissions:
  id-token: write
  contents: read

jobs:
  deploy-development:
    name: Deploy to Development
    uses: ./.github/workflows/reusable-aws-deploy.yml
    with:
      environment: development
      version: ${{ github.sha }}
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      AWS_ROLE_TO_ASSUME_PROD: ${{ secrets.AWS_ROLE_TO_ASSUME_PROD }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
