name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      ref:
        description: 'Git ref to deploy (tag, branch, or commit SHA)'
        required: true
        default: 'main'
        type: string
      version:
        description: 'Version label for the deployment (optional)'
        required: false
        type: string
      skip_tests:
        description: 'Skip unit tests'
        required: false
        default: false
        type: boolean

permissions:
  id-token: write
  contents: read

# Import shared configuration
env:
  GO_VERSION: '1.21'

jobs:
  unit-tests:
    name: Run Unit Tests
    uses: ./.github/workflows/reusable-test.yml
    with:
      go-version: ${{ github.event.inputs.go-version }}
    if: ${{ !inputs.skip_tests }}

  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    needs: unit-tests
    if: ${{ always() && (inputs.skip_tests || needs.unit-tests.result == 'success') }}
    uses: ./.github/workflows/reusable-aws-deploy.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      version: ${{ github.event.inputs.version || github.event.inputs.ref }}
      go-version: ${{ github.event.inputs.go-version }}
      skip-tests: true  # Tests already ran in the unit-tests job
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME_PROD }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
