name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      ref:
        description: 'Git ref to deploy (tag, branch, or commit SHA)'
        required: true
        default: 'main'
        type: string
      version:
        description: 'Version label for the deployment (optional)'
        required: false
        type: string

permissions:
  id-token: write
  contents: read

# Import shared configuration
env:
  GO_VERSION: '1.21'

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    uses: ./.github/workflows/reusable-aws-deploy.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      version: ${{ github.event.inputs.version || github.event.inputs.ref }}
      go-version: ${{ env.GO_VERSION }}
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      AWS_ROLE_TO_ASSUME_PROD: ${{ secrets.AWS_ROLE_TO_ASSUME_PROD }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
