name: Pull Request Environment

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

# Import shared configuration
jobs:
  deploy-pr:
    name: Deploy PR PR
    uses: ./.github/workflows/reusable-aws-deploy.yml
    with:
      environment: pr
      pr-number: ${{ github.event.pull_request.number }}
      outputs-file: pr-outputs.json
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME_DEVELOPMENT }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  comment-pr:
    name: Comment on PR
    needs: deploy-pr
    runs-on: ubuntu-24.04-arm
    if: ${{ needs.deploy-pr.outputs.deployment-outputs != '' }}
    steps:
      - name: Comment on PR
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const outputs = `${{ needs.deploy-pr.outputs.deployment-outputs }}`;
            const body = `## 🚀 PR Environment Deployed
            
            ### Environment Details:
            \`\`\`
            ${outputs}
            \`\`\`
            
            This pr environment will be automatically destroyed when the PR is closed.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
