name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

# Import shared configuration
env:
  GO_VERSION: '1.21'

jobs:
  unit-tests:
    name: Run Unit Tests
    uses: ./.github/workflows/reusable-test.yml
    with:
      go-version: ${{ env.GO_VERSION }}

  release-please:
    name: Release Please
    needs: unit-tests
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    
    steps:
      # Create a GitHub App token instead of using GITHUB_TOKEN
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      
      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          release-type: go
          package-name: aws-infra-sandbox
          changelog-types: |
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":false},
              {"type":"docs","section":"Documentation","hidden":false},
              {"type":"perf","section":"Performance Improvements","hidden":false},
              {"type":"refactor","section":"Code Refactoring","hidden":false}
            ]

  deploy-staging:
    name: Deploy to Staging
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    uses: ./.github/workflows/reusable-aws-deploy.yml
    with:
      environment: staging
      version: ${{ needs.release-please.outputs.tag_name }}
      go-version: ${{ env.GO_VERSION }}
      skip-tests: true  # Tests already ran in the unit-tests job
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      AWS_ROLE_TO_ASSUME_PROD: ${{ secrets.AWS_ROLE_TO_ASSUME_PROD }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  test-staging:
    name: Test Staging Deployment
    needs: [release-please, deploy-staging]
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release_created }}
    outputs:
      tests_passed: ${{ steps.integration_tests.outputs.tests_passed }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.release-please.outputs.tag_name }}
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Run Integration Tests
        id: integration_tests
        run: |
          echo "Running integration tests against staging environment..."
          # Add your integration tests here
          # For now, we'll just simulate a successful test
          echo "Integration tests passed!"
          echo "tests_passed=true" >> $GITHUB_OUTPUT
      
      - name: Test Summary
        run: |
          echo "## Staging Test Results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Tests completed successfully" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Details:**" >> $GITHUB_STEP_SUMMARY
          echo "- **Version:** ${{ needs.release-please.outputs.tag_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment:** staging" >> $GITHUB_STEP_SUMMARY
          echo "- **Test Time:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY

  deploy-production:
    name: Deploy to Production
    needs: [release-please, test-staging]
    if: ${{ needs.release-please.outputs.release_created && needs.test-staging.outputs.tests_passed == 'true' }}
    uses: ./.github/workflows/reusable-aws-deploy.yml
    with:
      environment: production
      version: ${{ needs.release-please.outputs.tag_name }}
      go-version: ${{ env.GO_VERSION }}
      skip-tests: true  # Tests already ran in the unit-tests job
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      AWS_ROLE_TO_ASSUME_PROD: ${{ secrets.AWS_ROLE_TO_ASSUME_PROD }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
