name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      go-version:
        description: "The Go version to use"
        required: true
    outputs:
      tests-passed:
        description: "Whether all tests passed"
        value: ${{ jobs.test.outputs.tests-passed }}

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    outputs:
      tests-passed: ${{ steps.run_tests.outputs.tests-passed }}
    
    steps:
      - name: Install dependencies
        run: |
          cd infra && go mod tidy
          for dir in functions/*; do
            if [ -d "$dir" ]; then
              cd $dir && go mod tidy && cd ../../
            fi
          done
      
      - name: Run unit tests
        id: run_tests
        run: |
          echo "Running unit tests..."
          
          # Run tests for infrastructure code
          cd infra && go test -v ./... && cd ..
          
          # Run tests for all Lambda functions
          for dir in functions/*; do
            if [ -d "$dir" ]; then
              echo "Testing $dir..."
              cd $dir && go test -v ./... && cd ../../
            fi
          done
          
          echo "All tests passed!"
          echo "tests-passed=true" >> $GITHUB_OUTPUT
        
      - name: Test Summary
        run: |
          echo "## Unit Test Results" >> $GITHUB_STEP_SUMMARY
          echo "✅ All unit tests passed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Details:**" >> $GITHUB_STEP_SUMMARY
            echo "- **Go Version:** $(go version | awk '{print $3}')" >> $GITHUB_STEP_SUMMARY
          echo "- **Test Time:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
