name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Import shared configuration
env:
  GO_VERSION: '1.21'

jobs:
  unit-tests:
    name: Run Unit Tests
    uses: ./.github/workflows/reusable-test.yml
    with:
      go-version: ${{ env.GO_VERSION }}

  cdk-synth:
    name: CDK Synthesis
    needs: unit-tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Install CDK
        run: npm install -g aws-cdk

      - name: CDK Synth
        run: make cdk-synth
