name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Import shared configuration
env:
  GO_VERSION: '1.21'

jobs:
  setup:
    name: Setup Environment
    uses: ./.github/workflows/reusable-setup.yml
    with:
      go-version: ${{ env.GO_VERSION }}

  test:
    name: Run Tests
    needs: setup
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Install dependencies
        run: |
          cd infra && go mod tidy
          for dir in functions/*; do
            if [ -d "$dir" ]; then
              cd $dir && go mod tidy && cd ../../
            fi
          done

      - name: Run tests
        run: make test

      - name: CDK Synth
        run: make cdk-synth
